<div align='center'><h1>Word Embedding With gensim</h1></div>

Word embedding also reffered to as distributed semantic model or semantic vector space or vector space model is a language modeling and feature learning technique that clusters similar words together. The most commond word embedding vectors are word2vec (Google), Glove (Stanford) and fastest (Facebook). Word embedding is applied in text classification, document clustering,dimensional reduction,topic modeling, feature generation among other NLP tasks such as sentiment analysis.<p>
Unlike the Latent Semantic Analysis technique that ignores words order and context the word embedding technique considers the order of words and context in the sentence.</p>
<p>Word2Vec employs the Continous Bag of Word model (CBOW) and Skip-gram model</p>

Install gensim

In [1]:
# !pip install gensim

Import libraries

In [2]:
import pandas as pd
import numpy as np

from nltk.tokenize import word_tokenize
import gensim


import warnings
import time

In [3]:
warnings.filterwarnings('ignore')
start_time=time.time() # start time counter 

Load data from csv

In [4]:
train=pd.read_csv('datasets/Sentiment Analysis on Movie Reviews/train.tsv',sep='\t')
test=pd.read_csv('datasets/Sentiment Analysis on Movie Reviews/test.tsv',sep='\t')

Given a tokenized text below

In [5]:
sentence = [['first', 'sentence'], ['second', 'sentence'],['The','quick','brown','fox','jumped','over','the','lazy','dog']]

In [6]:
sentence

[['first', 'sentence'],
 ['second', 'sentence'],
 ['The', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']]

Creating our word2vec model

In [7]:
model=gensim.models.Word2Vec(sentence, min_count=1)
model

Retrieve trained tokens

In [8]:
print(model.wv.vocab)

{'first': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42780>, 'sentence': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D427B8>, 'second': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42898>, 'The': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D429B0>, 'quick': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42B00>, 'brown': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42860>, 'fox': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42DD8>, 'jumped': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42EB8>, 'over': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42F28>, 'the': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42F60>, 'lazy': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42F98>, 'dog': <gensim.models.keyedvectors.Vocab object at 0x00000122B2D42FD0>}


Retrieve specific token

In [9]:
model['brown']

array([ 1.3444239e-03,  1.1104505e-03,  3.6670668e-03, -3.0380755e-03,
       -3.3615467e-03, -1.9463634e-03, -1.2481274e-03,  1.0538081e-03,
       -3.6050205e-03,  4.2925994e-03, -2.9276311e-05,  3.1682974e-04,
       -4.9738334e-03, -3.5612884e-03,  2.7165341e-03,  2.2008005e-03,
        1.5345173e-03,  3.3954033e-03,  1.5392535e-03, -4.4847829e-03,
       -3.9660102e-03, -1.9249116e-03,  1.3263862e-03,  3.2848583e-03,
       -2.3643472e-03, -4.2245239e-03, -3.3974333e-03, -4.3180822e-03,
       -4.0708003e-03,  3.6243810e-03, -2.9957425e-03,  4.5632175e-03,
       -2.4008495e-03,  2.2425840e-03,  1.4362979e-04,  3.1948423e-03,
        8.5834594e-04,  7.6305954e-04, -2.6896708e-03,  2.0214629e-03,
        3.9405557e-03, -3.4368099e-03, -1.7015096e-04, -2.3499890e-03,
       -3.2946263e-03,  4.4315797e-03, -2.5225764e-03, -7.3602569e-04,
        6.7232491e-04,  1.1447320e-03,  1.9797492e-03,  4.5907195e-03,
       -3.4033970e-03, -3.6840437e-03,  1.5390447e-03, -2.4238331e-03,
      

In [10]:
model['fox']

array([-4.1620326e-03,  2.8649466e-03,  3.3951448e-03,  4.2346497e-03,
        2.7630790e-03,  2.6403097e-03, -1.6289607e-03,  1.5152727e-03,
        4.8343372e-03,  4.7482122e-03, -9.8178803e-04, -1.1004630e-03,
       -3.2885119e-03,  2.8099411e-03,  2.5624995e-06,  4.7511309e-03,
       -1.0801874e-03, -2.5383008e-03,  5.3330505e-04, -7.9630314e-05,
       -4.1048969e-03,  1.2623504e-03, -2.6208479e-03, -2.5262889e-03,
       -2.1007687e-03,  8.2671823e-04, -2.3572717e-03, -4.5172204e-03,
        3.4260803e-03,  2.0435983e-03, -4.4283401e-03, -9.6844096e-04,
        4.9431529e-03,  2.0875544e-03, -2.7192975e-03,  3.5008455e-03,
        2.4198235e-03, -4.4839000e-03, -3.9422647e-03,  4.8295613e-03,
        2.6938976e-03,  3.7575772e-03, -3.4073009e-03,  6.0748169e-04,
       -3.5731371e-03, -4.6345843e-03, -2.1076205e-03, -2.8793234e-03,
        2.5038333e-03, -5.8214759e-05, -5.5383513e-04,  4.9163834e-03,
       -3.4966357e-03, -1.8735010e-04, -6.0397488e-05,  1.8623138e-03,
      

<h5>Out of Vocabulary word problem (OOV)</ h5>

This is a major weakness of the word embedding where words that are not represented in the training corpus are not mapped to any vector space.

If we use the word 'India' which is not in the training corpus we get an error since the model doesn't recognize it.

In [11]:
model['India']

KeyError: "word 'India' not in vocabulary"

The Out of Vocabulary word problem is also case sensitive i.e the word fox and Fox are two different words.

In [12]:
model['fox']

array([-4.1620326e-03,  2.8649466e-03,  3.3951448e-03,  4.2346497e-03,
        2.7630790e-03,  2.6403097e-03, -1.6289607e-03,  1.5152727e-03,
        4.8343372e-03,  4.7482122e-03, -9.8178803e-04, -1.1004630e-03,
       -3.2885119e-03,  2.8099411e-03,  2.5624995e-06,  4.7511309e-03,
       -1.0801874e-03, -2.5383008e-03,  5.3330505e-04, -7.9630314e-05,
       -4.1048969e-03,  1.2623504e-03, -2.6208479e-03, -2.5262889e-03,
       -2.1007687e-03,  8.2671823e-04, -2.3572717e-03, -4.5172204e-03,
        3.4260803e-03,  2.0435983e-03, -4.4283401e-03, -9.6844096e-04,
        4.9431529e-03,  2.0875544e-03, -2.7192975e-03,  3.5008455e-03,
        2.4198235e-03, -4.4839000e-03, -3.9422647e-03,  4.8295613e-03,
        2.6938976e-03,  3.7575772e-03, -3.4073009e-03,  6.0748169e-04,
       -3.5731371e-03, -4.6345843e-03, -2.1076205e-03, -2.8793234e-03,
        2.5038333e-03, -5.8214759e-05, -5.5383513e-04,  4.9163834e-03,
       -3.4966357e-03, -1.8735010e-04, -6.0397488e-05,  1.8623138e-03,
      

In [13]:
model['Fox']

KeyError: "word 'Fox' not in vocabulary"

In [14]:
def document_vecors(text):
    doc_vectors=[word for word in list(text) if word in model.wv.vocab]
    return np.mean(model[doc_vectors], axis=0)

In [15]:
document_vecors(['brown','fox'])

array([-1.40880444e-03,  1.98769849e-03,  3.53110582e-03,  5.98287093e-04,
       -2.99233827e-04,  3.46973189e-04, -1.43854413e-03,  1.28454040e-03,
        6.14658347e-04,  4.52040602e-03, -5.05532196e-04, -3.91816604e-04,
       -4.13117278e-03, -3.75673641e-04,  1.35954830e-03,  3.47596570e-03,
        2.27164943e-04,  4.28551226e-04,  1.03627925e-03, -2.28220667e-03,
       -4.03545331e-03, -3.31280637e-04, -6.47230831e-04,  3.79284727e-04,
       -2.23255809e-03, -1.69890281e-03, -2.87735253e-03, -4.41765133e-03,
       -3.22359963e-04,  2.83398968e-03, -3.71204130e-03,  1.79738831e-03,
        1.27115170e-03,  2.16506934e-03, -1.28783390e-03,  3.34784389e-03,
        1.63908477e-03, -1.86042022e-03, -3.31596774e-03,  3.42551200e-03,
        3.31722666e-03,  1.60383643e-04, -1.78872596e-03, -8.71253666e-04,
       -3.43388179e-03, -1.01502286e-04, -2.31509842e-03, -1.80767453e-03,
        1.58807915e-03,  5.43258619e-04,  7.12957000e-04,  4.75355145e-03,
       -3.45001649e-03, -

<h5>Creating embedding from dataframe data<h5>

In [16]:
train.head()

PhraseId  SentenceId                                             Phrase  \
0         1           1  A series of escapades demonstrating the adage ...   
1         2           1  A series of escapades demonstrating the adage ...   
2         3           1                                           A series   
3         4           1                                                  A   
4         5           1                                             series   

   Sentiment  
0          1  
1          2  
2          2  
3          2  
4          2

Tokenize the sentences to words

In [17]:
train['token']=train['Phrase'].apply(lambda x: word_tokenize(x))

Create Word2Vec model

In [18]:
sentiment_w2v=gensim.models.Word2Vec(train['token'], size=500, window=10, min_count=1, iter=20)

Vector size/embedding dimension

In [19]:
sentiment_w2v.vector_size

500

Total number of words in the embedding

In [20]:
len(sentiment_w2v.wv.vocab)

18238

View vocabulary

In [21]:
# print(list(sentiment_w2v.wv.vocab))

Get similar words

In [22]:
sentiment_w2v.most_similar(['rain'],topn=10)

[('coat', 0.7069823741912842),
 ('sweaty', 0.6475549340248108),
 ('shopping', 0.6032543182373047),
 ('desert', 0.5296441316604614),
 ('lameness', 0.5287156701087952),
 ('Characterisation', 0.5250074863433838),
 ('Stay', 0.515375018119812),
 ('bathtub', 0.4931764006614685),
 ('benchmark', 0.4913652837276459),
 ('redone', 0.48827600479125977)]

Get words similar to 'rain' or 'run'

In [23]:
sentiment_w2v.wv.most_similar(positive=['rain','run'],topn=10)

[('bathtub', 0.48297005891799927),
 ('coat', 0.4805057644844055),
 ('hack-and-slash', 0.47248774766921997),
 ('shopping', 0.4706310033798218),
 ('gas', 0.46871045231819153),
 ('amok', 0.45066356658935547),
 ('police', 0.4446251094341278),
 ('stand-up-comedy', 0.4429571032524109),
 ('desert', 0.44139930605888367),
 ('broke', 0.4371606111526489)]

Get disimilar words

In [24]:
sentiment_w2v.wv.doesnt_match(['raining','bad','morning'])

'bad'

Get similarity measure between two words

In [25]:
sentiment_w2v.similarity('rain','sun')

0.16102272

Load google word2vec pre-trained embedding

In [26]:
# import gensim.downloader as api
# wv_embedding = api.load('word2vec-google-news-300')

In [27]:
# end time for running the entire notebook
end_time=time.time()
print(end_time-start_time)

55.4943790435791


<div align='center'><h1>Conclusion<h1/><div />

Word Embedding is a powerful technique of representing text in vector form. This technique ensures that the syntactic and semantic aspect of the text is preserved. By preserving the context of each word in the text we get to infere correctly to the meaning of each word in the discourse of communication. We have looked at Word2Vec which is one of the implementation of Word Embedding. Other Word embedding implementations include glove, and fasttext.<br /><br />
One of the challenges of word embedding is the out of vocabulary word problem. The word that was not in the training corpus for embedding cannot be mapped into any vector space. This is a major challenges since the human language keeps evoling and new vocabularies are being invented daily not to mention errors the exisiting vocabularies by users.